const subData = [
    {
        sName : "The Godfather",
        bOption : "Rye bread",
        subSauces : "Mayonnaise",
        sIngredients : "Lettuce",
        sIngredients2 : "Bacon",
        sIngredients3 : "Cheddar Cheese",
        sIngredients4 : "Tomatoes",
        sIngredients5 : "Cucumber",
        subPrice: 80,
    },
    {
        sName : "The Breakfast Club",
        bOption : "Ciabatta",
        subSauces : "Tomato Sauce",
        sIngredients : "Basil",
        sIngredients2 : "Bacon",
        sIngredients3 : "Egg",
        sIngredients4 : "Ham",
        sIngredients5 : "Cheddar Cheese",
        subPrice: 90,
    },
    {
        sName : "The Star Wars",
        bOption : "Whole Grain",
        subSauces : "Mayonnaise",
        sIngredients : "Tomato",
        sIngredients2 : "Lettuce",
        sIngredients3 : "Egg",
        sIngredients4 : "Sliced Turkey",
        sIngredients5 : "Basil",
        subPrice: 75,
    },
    {
        sName : "The Jurassic Park",
        bOption : "Rye bread",
        subSauces : "Sriracha",
        sIngredients : "Lettuce",
        sIngredients2 : "Onion",
        sIngredients3 : "Tomatoes",
        sIngredients4 : "Cucumber",
        sIngredients5 : "Cheddar Cheese",
        subPrice: 90,
    }
]

    const subData2 = [
    {
        sName : "The Lord of the Rings",
        bOption : "Rye bread",
        subSauces : "Sweet Chilli",
        sIngredients : "Lettuce",
        sIngredients2 : "Ham",
        sIngredients3 : "Tomatoes",
        sIngredients4 : "Basil",
        sIngredients5 : "Egg",
        subPrice: 110,
    },
    {
        sName : "The Harry Potter",
        bOption : "Ciabatta",
        subSauces : "Mayonnaise",
        sIngredients : "Lettuce",
        sIngredients2 : "Basil",
        sIngredients3 : "Steak",
        sIngredients4 : "Carrots",
        sIngredients5 : "Cheddar Cheese",
        subPrice: 150,
    },
    {
        sName : "The Pulp Fiction",
        bOption : "Ciabatta",
        subSauces : "Mustard",
        sIngredients : "Ham",
        sIngredients2 : "Lettuce",
        sIngredients3 : "Carrots",
        sIngredients4 : "Basil",
        sIngredients5 : "Cheddar Cheese",
        subPrice: 60,
    },
    {
        sName : "The Titanic",
        bOption : "Ciabatta",
        subSauces : "Sweet Chilli",
        sIngredients : "Cucumber",
        sIngredients2 : "Jalapenos",
        sIngredients3 : "Carrots",
        sIngredients4 : "Basil",
        sIngredients5 : "Lettuce",
        subPrice: 75,
    }

]

